### ISSUE TITLE
TestAPI should support input manipulation

### ISSUE THREAD

**Issue by alcooper91** [immersive-web/webxr-test-api#11]
The API currently supports moving the input around, but there's no officially listed way to send clicks (to test input events), or to emulate whether a controller is present or not (to test, e.g. Gamepad SameObject properties and inputsourcechangeevents), or to change the Handedness of the controller.

There should also be some mention of the target ray mode for testing SameObject properties and testing that other properties are null when required by the specified TargetRayMode.

**Comment by Manishearth** [comment]
> There should also be some mention of the target ray mode for testing SameObject properties and testing that other properties are null when required by the specified TargetRayMode.

Not sure what you mean, #10 has a targetRayMode

**Comment by alcooper91** [comment]
Yes, this was before I had reviewed #10/it had that.  I think once we merge it, we can close this issue.

**Comment by Manishearth** [comment]
Oh I see.
