### ISSUE TITLE
Clarify simulateResetPose() intended usage

### ISSUE THREAD

**Issue by alcooper91** [immersive-web/webxr-test-api#12]
I'm not sure given the current state of the spec, what the intention for simulateResetPose is, we should consider if it's still needed, and if it is add clarification

**Comment by Manishearth** [comment]
I think the idea is to basically trigger the onreset event.

On cardboard and oculus, you can make this happen by holding down home until the origin is reset. It may be worth passing a new reference origin to this method.

Once we settle on an API I plan to fill in the explainer with information on each method.

**Comment by alcooper91** [comment]
I believe #10 also removed this method? SO once that's merged we could close this.

**Comment by Manishearth** [comment]
Lol. We may need to add it again, but we don't need it for an MVP.
