### ISSUE TITLE
Should methods return promises

### ISSUE THREAD

**Issue by alcooper91** [immersive-web/webxr-test-api#13]
If all methods return promises there would be substantial changes to the existing tests, but they would reliably ensure that device state has been updated before proceeding with the test.

**Comment by alcooper91** [comment]
See discussion here: https://github.com/immersive-web/webxr-test-api/pull/10#discussion_r293175757

**Comment by Manishearth** [comment]
> If all methods return promises there would be substantial changes to the existing tests

We already need substantial changes to the existing tests  :smile: 

At the F2F we discussed how much we want to change the API and the rough verdict was "it's totally fine to change it completely".

**Comment by Manishearth** [comment]
(Most tests would also be able to ignore the promise. Furthermore, most tests won't even _need_ these methods since we allow setting almost everything on init)

**Comment by Manishearth** [comment]
tentative PR at https://github.com/immersive-web/webxr-test-api/pull/18 . I'm okay with merging, feel free to merge if you agree. Otherwise we can continue discussion here, or solicit wider input.

**Comment by alcooper91** [comment]
Merged because I think we were both in agreement that we liked the concept behind the pattern, but re-opening the issue to indicate that we're still soliciting discussion.

**Comment by Manishearth** [comment]
sounds good

**Comment by alcooper91** [comment]
Hmm, I've had a chance to think about this over the weekend and I'm thinking that most tests that would maybe be okay without an RAF, probably are also okay to just set that state before the test starts, and most other tests would require a RAF anyway.
Does it feel like we're complicating the return/the tests we have to write, when we could just specify that the state needs a RAF to propogate?

**Comment by Manishearth** [comment]
Works for me! Want to make the PR speccing that?
