### ISSUE TITLE
Determine appropriate reference space origin

### ISSUE THREAD

**Issue by alcooper91** [immersive-web/webxr-test-api#14]
We should determine the appropriate reference space origin to use for XRRigidTransforms
https://github.com/immersive-web/webxr-test-api/pull/10/files#r293135511

**Comment by Manishearth** [comment]
At the moment my arbitrary choice in #10 is "The viewer's origin at t=0", because this has an unambiguous meaning across devices (making it easier to reason about 3DOF devices in tests)

An alternate choice is "The viewer's feet at t=0", but this requires factoring in `eyeLevel`.

**Comment by alcooper91** [comment]
What if we just assumed "Identity" is the reference space origin, and then any viewerOrigin that we specify in the FakeXRDeviceInit is simply the initial location of the device.  This also helps ensure that we can reason across 3DOF devices or devices that we want to show up as initially being "untracked"

**Comment by Manishearth** [comment]
> What if we just assumed "Identity" is the reference space origin,

(this doesn't quite make sense, we're trying to find a _physical_ origin as a reference, we're defining _what identity is_)

> and then any viewerOrigin that we specify in the FakeXRDeviceInit is simply the initial location of the device


This could work but this will needlessly complicate implementations imo. The problem is that the local and local-floor reference spaces work relative to the initial position of the device. Unrelatedly, most 3dof devices report coordinates relative to the initial position of the device, and mirroring that is nice for ease of implementation.

**Comment by alcooper91** [comment]
I think I had misread the comment: 
// When used as a native origin, it is in the reference space
// where the viewer's native origin is identity at initialization
To assume that we were using the viewerOrigin in FakeXRDeviceInit as the origin (i.e. all getPose's should be offset by that initial value), but I think the intention is that what we put in, should be what we get out in a getPose (for a local reference space), which was my question of assuming "Identity",
I think there needs to be an updated comment/explanation somewhere along the lines of:
When used to set the viewerOrigin this is relative to the fake device's native origin, which is assumed to be Identity at creation.

Perhaps a comment for the FakeXRDeviceInit to indicate that it is how far the device has moved from it's native origin, which is assumed to be Identity (or 0,0,0 and no rotation)

**Comment by Manishearth** [comment]
Yeah., that works

**Comment by alcooper91** [comment]
Fixed by #31
