### ISSUE TITLE
Determine if navigator.xr.test object is the best practice

### ISSUE THREAD

**Issue by alcooper91** [immersive-web/webxr-test-api#15]
#10 Added the XRTest object as a singleton off of the navigator.xr object.  Determine what similar APIs do and if this is a best practice, or if simply creating an instance before running any tests would be sufficient.

**Comment by Manishearth** [comment]
An alternative is 

```webidl
interface XRTest {
  static Promise<FakeXRDevice> simulateDeviceConnection(FakeXRDeviceInit);
  static void simulateUserActivation(Function);
  static Promise<void> disconnectAllDevices();
};

```

As mentioned in https://github.com/immersive-web/webxr-test-api/pull/10/files#r293129632 , web specs typically prefer `navigator.foo` or `navigator.foo.bar` for singletons like this.

Another alternative is `navigator.xrtest` or something.

**Comment by alcooper91** [comment]
I think this is fine.
