### ISSUE TITLE
Example test

### ISSUE THREAD

**Issue by ryzngard** [immersive-web/webxr-test-api#2]
I think we should have a sample test showing the usage of the API. I'm still unclear on a few things, and having an example may help clear those up.

**Comment by paezagon** [comment]
That sounds like a good idea. I'm going to be a bit busy for about a week (deadline coming up) but I'll try to get something up later next week.

**Comment by paezagon** [comment]
I have uploaded https://github.com/immersive-web/webxr-test-api/blob/master/sample_test.html. 

This sample demonstrates how a test might look using the API. 

Does that help clarify?

**Comment by ryzngard** [comment]
Looking now, I'll open anything as new issues as needed. Thanks for putting this up!
