### ISSUE TITLE
No way to deactivate via FakeXRDeviceController

### ISSUE THREAD

**Issue by ryzngard** [immersive-web/webxr-test-api#3]
Currently there exists 

```
// Simulates the user activating the headset.
void simulateHeadsetActivation();
```

but no way to deactivate. Maybe we should have a property? Or add a mirrored `simulateHeadsetDeactivation() `

**Comment by paezagon** [comment]
Going over the spec, it looks like headset activation isn't yet specified. There is one open issue mentioning it, https://github.com/immersive-web/webxr/issues/277, but that seems to be it. Given that is the case we probably shouldn't try testing it as the behavior is not defined, and should remove the `simulateHeadsetActivation`. 

We can always add this in again when it gets into the spec.

**Comment by ryzngard** [comment]
Sounds great. I'll get a quick PR up
