### ISSUE TITLE
FakeXRDevice currently does not allow to signal AR support

### ISSUE THREAD

**Issue by bialpio** [immersive-web/webxr-test-api#44]
Currently, it is not possible to create an AR-capable FakeXRDevice. FakeXRDeviceInit only contains `required boolean supportsImmersive;` (probably from the times when AR sessions were a subtype of immersive sessions).

One potential solution would be to change the `required boolean supportsImmersive;` into an enum that'd mimic the XRSessionMode from main spec, something along the lines of:

```
enum FakeXRSessionMode {
  "inline",
  "immersive-vr",
  "immersive-ar"
};

partial dictionary FakeXRDeviceInit {
  required FakeXRSessionMode supportedSessionMode;
};
```

@Manishearth, @alcooper91 - WDYT?

**Comment by Manishearth** [comment]
Devices have to support inline, and can support multiple modes. I'd add a new supportsAR boolean.

**Comment by Manishearth** [comment]
We could also do an array of XRSessionModes, but then you need to update tests.

**Comment by alcooper91** [comment]
We could also do what we've done in the past which is define an array of XRSessionModes and it overrides whatever was set for "supportsImmersive", once we've had a chance to update the tests, we could deprecate supportsImmersive.

It feels a lot cleaner to indicate support for the XRSessionModes.

**Comment by alcooper91** [comment]
Hmm, though if someone wanted to implement the test API just for the core spec, they may not be able to support a device with an arbitrary session mode (even if requestSession and isSessionSupported should take the values).

**Comment by Manishearth** [comment]
That works for me. We should forbid "inline" from this array.

**Comment by bialpio** [comment]
I think we might be able to keep it a scalar that mirrors SessionMode. The user of the API ( = test) does not have a way of telling if the device used for inline session is the same one as the one used for immersive-vr session, so it should be sufficient to change the tests to always simulate connection of one device supporting inline session, and one more device supporting immersive-vr / immersive-ar session. That still would require changing all the tests though.

**Comment by Manishearth** [comment]
No, that precludes testing certain things like the implicit inline device
as well as simultaneous inline and immersive sessions.

Honestly that enum is probably not going to expand and if we're creating an
array of enum values where one value is forbidden we should just have
supportsImmersiveVr and supportsImmersiveAr flags.

**Comment by alcooper91** [comment]
Right but if it *does* expand we're in the business of just adding another enum to indicate support.

**Comment by Manishearth** [comment]
No, we can just add another boolean flag, but another mode is pretty rare.
At best we may have a handheld-ar mode, but it's unlikely. This has been
discussed a couple times.

**Comment by bialpio** [comment]
Ok, it seems to me that the easiest way to proceed would be to add `required boolean supportsImmersiveAR;` to `FakeXRDeviceInit` and rename `supportsImmersive` into `supportsImmersiveVR` for clarity.

**Comment by alcooper91** [comment]
Renaming supportsImmersive would break existing tests. 

Which part of the spec requires that all immersive devices support inline? I would think browsers may split up that support, so it may be fine to indicate that an attached device only supports immersive-vr for instance. 

While we think right now that the enum won’t change, it still feels a lot cleaner to me to specify a list of modes rather than adding multiple bools.

**Comment by Manishearth** [comment]
Oh, sorry, we require that all _browsers_ support a default inline device (https://immersive-web.github.io/webxr/#inline-xr-device). 

In that case a list of enum values seems fair.

**Comment by alcooper91** [comment]
So I believe the proposal is more-or-less:
```
partial dictionary FakeXRDeviceInit {
  sequence<XRSessionMode> supportedModes;
}
```
And for back-compat purposes have an algorithm that calls out something like: "if `supportedModes` is not set or of length zero, then:
if `supportsImmersive` is true, append `"immersive-vr"` to `supportedModes`
else append `"inline"` to `supportedModes`"

**Comment by alcooper91** [comment]
Actually, I think existing tests may expect all devices to report inline pose data currently. So the back-compat algorithm is probably something like:
"if `supportedModes` is of length zero, append `"inline"`.  If `supportsImmersive` is true, append `"immersive-vr"`"

**Comment by Manishearth** [comment]
Hmm, but we should then remove that later once the tests are updated.
