### ISSUE TITLE
Should we have SetHandedness/SetTargetRayMode/SetProfiles/SetSupportedButtons?

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr-test-api#46]
I don't think input sources ever _change_ this part of their state, and supporting this just for the mock API seems unnecessary. It introduced implementation complexity that is unnecessary for non-mock backends.

In general we should only support testing things that can actually happen; and not introduce additional implementation complexity.

cc @alcooper91

**Comment by Manishearth** [comment]
Furthermore if this stuff could change we'd probably want spec text in the core spec deciding how it is updated, and perhaps an event around it.

**Comment by alcooper91** [comment]
The spec text actually does allow for these things to change: https://immersive-web.github.io/webxr/#xrsession-change-input-source, and I believe the GamepadAPI allows for the supported buttons to change.

Handedness definitely can, and does, change.  If I'm remembering correctly, if a single controller is connected to OpenVr, it's handedness is "none", upon connecting a second controller, a handedness is assigned to each.

While I currently cannot think of any XR controllers that change supportedButtons in Xr (which would probably also change the profiles) or the target ray mode, such controllers do exist and it's not outside the realm of possibility that they could eventually become an XR controller. (e.g. Think of a Wii Controller which could have the nunchuck attached/detached thereby changing the buttons, or could be inserted into a "steering wheel" type device and therefore change it's target ray mode).

**Comment by alcooper91** [comment]
Even though some of these things aren't supported by existing items, the fact that the spec calls out an algorithm for them, implies that we should test them. Even if currently it feels a bit contrived.

**Comment by Manishearth** [comment]
Yeah, my mental model for testing those things was that we should use a new simulateDeviceConnection, but this makes more sense.
