### ISSUE TITLE
Should returning test devices be optional?

### ISSUE THREAD

**Issue by ryzngard** [immersive-web/webxr-test-api#5]
In the explainer it says requestDevice **MAY** return a test device.

What's blocking us from making it a requirement that requestDevice resolves to a test device if available? It seems likely we would want the tests to always run the same, and returning different sets of devices could result in more chaos than needed.

**Comment by paezagon** [comment]
The intention was that requestDevice will resolve to a test device if there is one. 

There is some ambiguity in the spec itself as to what device is returned when multiple devices are available. For most of our tests, this will not be an issue as the pattern will be 
Add a device
requestDevice, expect that it will be the added device
test additional properties

It might be worth calling this assumption out explicitly in the explainer. What do you think?

It might be good for the explainer to also define what should happen in the event that there's multiple devices, as it is also possible that these tests will be run on machines with real devices available. It would be good for the tests to have some way to disable all real devices to ensure consistent results. In the event that multiple test devices are added for a test, how would we determine which should be returned for test device? What sort of tests would this matter for?

**Comment by ryzngard** [comment]
Adding the intention to the explainer sounds good. 

For multiple devices, I think requiring that no real devices be returned while a test device is present would help with some of the ambiguity. For multiple test devices, maybe specify an order? I don't have a particular affinity to an order, but agreeing on one will help prevent any headaches in the future. Maybe just always return the last added?

**Comment by ryzngard** [comment]
Adding the intention to the explainer sounds good. 

For multiple devices, I think requiring that no real devices be returned while a test device is present would help with some of the ambiguity. For multiple test devices, maybe specify an order? I don't have a particular affinity to an order, but agreeing on one will help prevent any headaches in the future. Maybe just always return the last added?

**Comment by paezagon** [comment]
Agreed on the returning no real devices when a test device is present. 

For the multiple devices, I don't think that we can specify and order, because such an ordering would have to override whatever the implementation normally does in requestDevice(), and I think that would be bad. 
I think it would be better to specify in the spec that when more than one device is present, there is no way of knowing which device will be returned, and tests need to take that into account.

**Comment by ryzngard** [comment]
Good point. As long as it's open to interpretation in the API, the test API should be no different.

**Comment by alcooper91** [comment]
ISTM that paezagon's last comment is addressed by this line:
The promise returned from simulateDeviceConnection resolves with a FakeXRDevice, which can be used to control the fake XRDevice that has been created in the background. The fake device may be used in a session returned by navigator.xr.requestSession(), depending on how many devices have been created and how the browser decides to hand them out.
