### ISSUE TITLE
Parse a view resetting the projection matrix ?

### ISSUE THREAD

**Issue by svillar** [immersive-web/webxr-test-api#53]
In the [parse a view](https://immersive-web.github.io/webxr-test-api/#parse-a-view) algorithm, the step 8 resets the projection matrix to the one from the FakeXRViewInit as it was done previously in step 4 and potentially overwritting the value set in step 7.

**Comment by alcooper91** [comment]
Good catch. I *think* step 8 just needs to be removed, because the intention was that if fieldOfView is set that it overrides a set projection matrix.
