### ISSUE TITLE
Update Spec Text for pointerOrigin

### ISSUE THREAD

**Issue by alcooper91** [immersive-web/webxr-test-api#57]
For "gaze" and "screen" input sources pointerOrigin should be relative to the viewer origin.
For "target-ray" input sources, it should be relative to the grip's origin. (which may/may not always be tracked)
This more accurately simulates real devices, since the pointer is often moved by another XRSpace.

**Comment by alcooper91** [comment]
This arose because of web-platform-tests/wpt#22901

**Comment by Manishearth** [comment]
>  For "target-ray" input sources, it should be relative to the grip's origin. (which may/may not always be tracked)

If we do this we should also add a supportsGrip boolean so that even if you set a grip space, it can be hidden, since not all devices have grip spaces

**Comment by alcooper91** [comment]
I'm not sure that it's actually necessary, since it's currently possible to clear the gripOffset

If a device exists it *has* a coordinate space that can be defined, and so the pointerOffset is defined *in that space*. If a device doesn't have a gripOffset, that means that we just don't know where that space actually is, but if we did, we'd know that the target ray was located pointerOffset away from it's origin.

I'm having a hard time visualizing a case where an input source of target-ray *doesn't* have a gripOffset, (e.g. we don't know where it is), but the pointer offset is valid, as it seems like we're simultaneously saying "We don't know where it is, but we know where it is"

**Comment by alcooper91** [comment]
Or is the thought that maybe the *UA* knows where it is, but isn't exposing where it is to the site and is just saying "This is where it's pointing"?

If that's the scenario, that feels like a UA decision on a specific input type that I'm not sure is appropriate to incorporate to the test api.

**Comment by Manishearth** [comment]
> I'm having a hard time visualizing a case where an input source of target-ray doesn't have a gripOffset, (e.g. we don't know where it is), but the pointer offset is valid, as it seems like we're simultaneously saying "We don't know where it is, but we know where it is"

We do not require input sources to have a grip space, this is a choice the UA is allowed to make.

I don't like making the target ray space dependent on the grip space, this is kinda why I was advocating for it to be native. It's way easier to deal with things when everything isn't interdependent.

**Comment by Manishearth** [comment]
Another thing I realized: the pointer is not fundamentally an offset from the grip, anyway. Hololens' pointer, for example, is a straight line through the chest and grip. Doesn't matter as much for testing, but it would be good for the test API to match the basic concepts well.

**Comment by alcooper91** [comment]
The issue if it's *not* based on the grip space is that if my intention is to simulate "moving a controller" or "looking around and tapping select" I now have to update both the gripOffset *and* the pointerOffset by the same amount in the test, it adds extra boilerplate to simulate something that I'm not convinced there's a real-world analogue to.
This is especially true for gaze/screen input sources, where I may want to validate that things are no longer in the viewer pose and that a new object is at the end of my "pointer"

Given that the test api is intended to simulate some real device, whether or not the UA chooses to expose the gripSpace is not something that I think is in the bounds of the test-api to dictate. The Test API should be saying "There's an input source, it's here, and it's pointer is here." Defining the pointer in terms of an offset from where the input source is reduces the cognitive overhead of writing, understanding, and debugging the tests and reduces potential for unintended behaviors. If we are asserting that it's totally valid for the UA to *only* expose the pointer space (even for target-ray modes), and that it's a UA *choice* to expose it, then we shouldn't assert that it's present, only that if it's present it matches what we expect.

**Comment by alcooper91** [comment]
I think "gripOffset" may be a bit overloaded here, where as I think of it as "where the controller is"

For "gaze" and "viewer" "where the controller is" should be the viewerOrigin, for "target-ray" it should be the "gripOrigin"

**Comment by alcooper91** [comment]
I think the hololens pointer is then a gaze based pointer? Or it has no offset from the location of the controller.

**Comment by Manishearth** [comment]
> I think the hololens pointer is then a gaze based pointer? Or it has no offset from the location of the controller.

No, that's hololens 1, the hololens 2 pointer goes through your hand, it's just not _only_ attached to your hand.

> I think "gripOffset" may be a bit overloaded here, where as I think of it as "where the controller is"

Yeah, to me it's very clearly "the origin of the grip space", especially since it's called gripOrigin :)

**Comment by alcooper91** [comment]
I mean, it *is* the origin of the grip space, but the way I read this is that the origin of the grip space *should* be "where the controller is":
https://immersive-web.github.io/webxr/#dom-xrinputsource-gripspace

**Comment by alcooper91** [comment]
> > I think the hololens pointer is then a gaze based pointer? Or it has no offset from the location of the controller.
> 
> No, that's hololens 1, the hololens 2 pointer goes through your hand, it's just not _only_ attached to your hand.

Hmm, conceptually though *something* still drives that pointer right? The primary pointer is parented to whichever hand it determines should be "primary" and then if it can't detect either of those then presumably it's gaze-based?

And I think your argument is that you want to drive it as just a single synthetic "input source" that's a "target-ray" which has no grip?

**Comment by Manishearth** [comment]
> Hmm, conceptually though something still drives that pointer right? The primary pointer is parented to whichever hand it determines should be "primary" and then if it can't detect either of those then presumably it's gaze-based?

Yes, but the point is that the pointer is not an "offset on the grip", it's something weirder. What i'm trying to say is that the target ray is fundamentally it's own thing, not something with a straight offset relationship with the grip.

Worth noting: gaze and screen spaces don't have grip spaces, usually.

> And I think your argument is that you want to drive it as just a single synthetic "input source" that's a "target-ray" which has no grip?

Yes, i'd like to be able to represent input sources without grips, and I think they're fundamentally separate things that should be represented separately.

**Comment by alcooper91** [comment]
>Worth noting: gaze and screen spaces don't have grip spaces, usually.
Per the spec actually, gaze and screen spaces MUST NOT have a grip space. It feels like it's fairly uncontroversial to set the pointerOrigin for gaze/screen to be an offset from viewerOrigin rather than local space?

From here on out I'll be talking explicitly about target-ray input sources
There's a couple of ways I can see to represent the scenario you're talking about; though I'm not sure how much benefit there is:
1) Simply set the gripOrigin to identity. it's 'tracked" but you can set the pointerOrigin in "local" space at that point and pretend like it's not (any test that would be doing this could simply not care about what is exposed as the gripSpace)
2) Instead of using XRTargetRayMode define XRTargetRayModeInit, where we can add a new "target-ray" type like "untracked-target-ray"; the gripOrigin *must* never be set on this type, and pointerOrigin is therefore defined as being in the native space since gripSpace is a UA choice, tests that use untracked-target-ray MUST NOT assert anything about the grip space on those input sources.
3) Expose a setTrackedGrip (or similar). The pointerOrigin is still relative to whatever grip was set, (or identity if no grip is set), but it's a hint to the UA that it doesn't need to care about the gripOrigin except in determining pointerSpace. Similar to untracked-target-ray tests where trackedGrip is set to false MUST NOT assert anything about the grip space on those input sources.
4) Add a new member, pointerOffset; require that only one of pointerOrigin/pointerOffset are specified in init (and setting either afterwards overrides the other behavior). pointerOffset will be relative to the gripOrigin, and pointerOrigin will be a direct native space. This does sort of still allow for that "controlling the pointer independent of a controller's position" that I think will make tests harder to understand and I think makes the back-end a bit more confusing.

I took a quick look, just to document which tests are making these assumptions today (note that these are also the only tests that assert a specific value for the targetRaySpace matrix)
Tests which currently make use of tracked-pointer and assume it is offset by the gripSpace are:
getInputPose_pointer.https.html
xrReferenceSpace_originOffset.https.html
xrReferenceSpace_originOffsetBounded.https.html

Only one screen/gaze space input source appears to query the targetRaySpace at the moment and that is in:
ar_hittest_subscription_inputSources.https.html

**Comment by Manishearth** [comment]
oops, missed this last comment

>  It feels like it's fairly uncontroversial to set the pointerOrigin for gaze/screen to be an offset from viewerOrigin rather than local space?

Relatively, but still, I think targetRaySpace is defined in the spec as a native origin and we should be plugging directly into spec concepts as much as we can

------

> Expose a setTrackedGrip (or similar). 

We can fix this with a `grip_tracked` boolean, yes. But it feels clunky to me.

> Add a new member, pointerOffset; require that only one of pointerOrigin/pointerOffset are specified in init (and setting either afterwards overrides the other behavior). pointerOffset will be relative to the gripOrigin, and pointerOrigin will be a direct native space. 

This feels better to me. I think pointerOrigin should be a native origin, i have no problems with having an offset also be an option for tests where that makes more sense. All of these can be nullable (with behavior beng undefined if grip is null and offset is not).

setPointerOrigin and setPointerOffset can null out the other one. We can then use pointerOffset for the tests that actually need to care about it in this form (namely, the screen space one), and pointerOriign for ones which just need a pointer.

**Comment by alcooper91** [comment]
Floated the idea with some coworkers and the notion of having two ways to set the pointer seemed to just add additional complexity. It also seems like no tests are currently doing the scenario I imagined (e.g. moving just the viewer), but *are* in fact just moving the pointer. I think if we want to move the pointer relative to the controller, there's probably a couple of helpers we could write.
