### ISSUE TITLE
Undefined xr_debug for non-Chromium based browsers

### ISSUE THREAD

**Issue by svillar** [immersive-web/webxr-test-api#61]
The problem is that although is initialized to an empty function it's later redeclared to some chromium specific entity

```
    if (window.XRTest === undefined) {
       // Chrome setup
       await loadChromiumResources;
       xr_debug = navigator.xr.test.Debug;
     }
```

The condition is true also for WebKit based browsers

**Comment by svillar** [comment]
This was meant to be filled against wpt not the testing API.

**Comment by Manishearth** [comment]
It seems like these checks should be gated as chromiun-only somehow. The tests work as long as you implement XRTest, seems like not implementing it makes you hit a branch where WPT thinks you're chromium, which is bad.

**Comment by svillar** [comment]
Yeah I've already filled https://github.com/web-platform-tests/wpt/pull/23200 to fix it
