### ISSUE TITLE
"next animation frame" racy even when there are no callbacks

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr-test-api#64]
https://immersive-web.github.io/webxr-test-api/#xrsession-next-animation-frame

![image](https://user-images.githubusercontent.com/1617736/80742988-1991b980-8ad1-11ea-81fe-4012ee54ebba.png)

A problem is that even when there is no rAF callback queued up, [the rAF loop is supposed to keep ticking according to the original spec](https://immersive-web.github.io/webxr/#xr-animation-frame). So there might be a queued-up "empty" animation frame waiting on the event loop when a command is sent down to the backend.

Perhaps the "If such an operation is triggered outside of an XR animation frame" case should unconditionally be "queue it up for the next frame or the next-to-next-frame, whichever has not started executing yet"?

Essentially, this means that when writing tests, we may need to skip a frame to flush these, or use events (e.g. https://github.com/web-platform-tests/wpt/blob/4d413415dd8c6a0dc18d173071525dc0d12b11a6/webxr/hit-test/ar_hittest_subscription_inputSources.https.html#L57-L59 would use an oninputsourceschange event)

cc @alcooper91

**Comment by alcooper91** [comment]
Even in the case where we are using events, we may still need to run the animation frames so that the data can be surfaced (e.g. UAs may opt to only send input data with frames)

I definitely don't remember that requirement from the main spec; was that a recent change?

**Comment by alcooper91** [comment]
Test-wise (outside of the spec) it may be good to write some wrapper util like "onNextAnimationFrame(session, rAFCallback)" which just does something like:
```
session.requestAnimationFrame(() => {
  session.requestAnimationFrame(rAFCallback);
});
```
And we should be writing tests to use that for the first animation frame they need (and hopefully every subsequent animation frame is outside the loop).

**Comment by Manishearth** [comment]
> Even in the case where we are using events, we may still need to run the animation frames so that the data can be surfaced (e.g. UAs may opt to only send input data with frames)

Right, the XR animation frames need to tick regardless of `rAF()` being queued

> I definitely don't remember that requirement from the main spec; was that a recent change?

It's always been there

---

the test plan seems good. I'd use events whenever possible so we don't have to deal with this at all.

**Comment by Manishearth** [comment]
Like, for the most part this is going to occur when setting things on init, and mos of that happens through a struct, except for input sources and hit test worlds. Input sources have an event to listen to. Hit test worlds don't but we can use your helper there.

**Comment by alcooper91** [comment]
Right; but I'd just like to caveat that I don't think it's fair to say:
simulateInputSourceConnection
// wait for event without queing a rAF

**Comment by Manishearth** [comment]
Oh! I see. Yeah, this seems fair to me. It's not actually valid for UAs to do this, FWIW, but I'm okay with the other solution.

We tie select events to animation frames, for example. I think everyone is a little bit wrong here, in a way that doesn't practically matter.

**Comment by alcooper91** [comment]
> It's not actually valid for UAs to do this, FWIW...

Can you elaborate on what "this" is in this context?

**Comment by Manishearth** [comment]
@alcooper91 only send events if rAF() has been called

This is why the XR animation frame loop runs regardless of rAF being queued up

(Actually, come to think of it, we tie select events to animation frames, but we don't require rAF for that)

**Comment by Manishearth** [comment]
Basically, it is totally valid for a UA to only deal with events on a per-frame basis, but if a session is running and visible there should _always_ be a frame loop running, just that it will hit script and not trigger any rAF callbacks.

Given that, it should be okay to write tests to use oninputsourceschange
