### ISSUE TITLE
Devices's supported features should be specified per mode

### ISSUE THREAD

**Issue by svillar** [immersive-web/webxr-test-api#65]
When simulateDeviceConnection() [is described](https://immersive-web.github.io/webxr-test-api/#dom-xrtest-simulatedeviceconnection) the supported modes and supported features for the simulated device are specified independently. However the WebXR spec when talking about the `XRDevice` [states](https://immersive-web.github.io/webxr/#xr-device-concept) that

> Each XR device has a list of enabled features for each XRSessionMode in its list of supported modes, which is a list of feature descriptors which MUST be initially an empty list.

So I guess that we either:

- Change the FakeXRDeviceInit and the algorithm to support different features per mode, *or*
- Modify the algorithm explaining that the list of features are supported for all the specified modes

**Comment by alcooper91** [comment]
My preference would be to modify the algorithm to state that it's valid for all specified modes. We've been trying to minimize the number of back-compat breaking changes; and given that most tests really only test one mode I don't think that there's much to be gained by splitting the features per mode.

**Comment by Manishearth** [comment]
My preference is for the latter as well, for the same reasons.

Test API users who wish to have different modes supporting different features should create multiple devices.

**Comment by svillar** [comment]
Cool, I agree with you both FWIW. Do you want me to propose a change of the text on a PR?

**Comment by Manishearth** [comment]
Go for it!
