### ISSUE TITLE
WebXR Input

### ISSUE THREAD

**Issue by paezagon** [immersive-web/webxr-test-api#7]
We should be able to test the WebXR input API. 

Suggested Addition: 
```
partial interface FakeXRDeviceController {
  Promise<FakeXRInputSourceController>  
        simulateInputSourceConnection(FakeXRInputSourceInit);
}

interface FakeXRInputSourceInit {
  XRHandedness handedness;
  XRPointerOrigin pointerOrigin;
};

interface FakeXRInputSourceController {
  void setPose(
    boolean emulatedPosition, 
    Float32Array pointerMatrix, 
    Float32Array? gripMatrix);
};
```

**Comment by ryzngard** [comment]
We should probably add `Promise<FakeXRInputSourceController> simulateInputSourceConnection(FakeXRInputSourceInit);` directly to XRTest right? Similar to how `simulateDeviceConnection` is. Otherwise, everything looks good to me

**Comment by paezagon** [comment]
The issue I see with that is that if you have added two devices, which device should the controller be associated with?

It is unlikely that we will ever be in this situation, given that we can have multiple fake devices, we should account for the possibility. 

This also assumes that input sources are associated with a device, but given that I haven't run into any headset independent XR input devices, I think it's a reasonable assumption.

**Comment by ryzngard** [comment]
You're right that there is a little weirdness if we associate outside of a session. I missed that this was tied to the already existing FakeXRDeviceController, which makes total sense. There will still be ambiguity to mapping of device to session, but that's being discussed in #5 . This proposal looks good to me!
